name = "verify-hydra-worker"
main = "index.js"
compatibility_date = "2026-06-07"

[vars]
SUPABASE_URL = "https://lkedheatwbdbkfblehsg.supabase.co"
HCAPTCHA_SITEKEY = "e41c956e-5422-4130-8496-6388de0ece2e"
FRONTEND_BASE_URL = "https://hydra-verify.nexus-02.workers.dev"

# Secrets (set via `wrangler secret put <NAME>`)
# INTERNAL_API_KEY = "onyxax_54154897845ssafddalwjakdnsbsajsakdsdhsaldaslduuuhsuu54"
# SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
